spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.50.104:8848

server:
  port: 40000

logging:
  level:
    com.gxd.gulimall.search: debug


