spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.11:8848
  thymeleaf:
    cache: false

server:
  port: 40000

logging:
  level:
    com.gxd.gulimall.search: debug


