spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.89.210.14:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: gulimall-ware

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.50.104:8848

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 50000


#日志打印级别debug
logging:
  level:
    com.gxd.gulimall.ware: debug


